###
POST http://localhost:8080/board/reply/insert
Content-Type: application/json

{
  "contentNumber": "7",
  "id": "admin",
  "writer": "관리자",
  "comment": "ㅋㅋㅋㅋㅋㅋㅋㅋ",
  "secret": "N"
}


###
POST http://localhost:8080/board/notice/insert
Content-Type: application/json;charset=utf-8

{
  "seq":"1",
  "title":"테스트 입니다.",
  "writer":"관리자",
  "content":"test contents :)"
}


###
POST http://localhost:8080/board/notice/create.do
Content-Type: application/json

{
  "seq":"1",
  "title":"테스트 입니다.",
  "writer":"관리자",
  "content":"test contents :)"
}


###
GET http://localhost:8080/board/notice/test?title=hi

###
POST http://localhost:8080/board/main/call-post
Content-Type: application/json

{"title": "Jeon"}

###
GET http://localhost:8080/board/main/test

###
POST http://localhost:8080/board/main/input.do



